### PR TITLE
Update sanitizeTitle.ts

### PR DESCRIPTION
**Pull request by buggithubs**
Add
Filtering and replacement of special characters in book names / and Unicode U+003A ':'

### CODE REVIEW

**Comment by zhaohongxuan** [comment]
> Add Filtering and replacement of special characters in book names / and Unicode U+003A ':'

**Comment by zhaohongxuan** [comment]
I reviewed the Change file and found that actually you replaced the Chinese Colon `Unicode U+FF1A` instead of The `Unicode U+003A ':' ` , the English colon had been repaced before,  and I think  it is unnecessory to replace `Chinese Colon` since it will not prevent the note file creation.

**Comment by buggithubs** [comment]
image
`失落的卫星 : 深入中亚大陆的旅程`

I was unable to create this title locally using obsidian 1.1.16 test.
He uses the Unicode U+003A ':'

**Comment by zhaohongxuan** [comment]
> 失落的卫星 : 深入中亚大陆的旅程

image
我用最新版的插件同步是可以成功的，冒号会被替换为空格，你把控制台保存的信息贴出来吧

**Pull request closed without merging**
